# Generated by Django 4.1.4 on 2023-03-24 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrebanco', models.CharField(blank=True, max_length=30)),
                ('numerocuenta', models.CharField(blank=True, max_length=30)),
                ('tipocuenta', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'tb_cuenta',
            },
        ),
        migrations.CreateModel(
            name='negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=13)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('fotodenegocio', models.ImageField(blank='', default='', upload_to='fotos/')),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('paginaweb', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'negocio',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle1', models.CharField(blank=True, max_length=100)),
                ('detalle2', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imag', models.ImageField(blank='', default='', upload_to='fotos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_producto',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=20)),
                ('cod', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_rol',
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('clave', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usurioarol', to='cuenta.rol')),
            ],
            options={
                'db_table': 'tb_usuario',
            },
        ),
        migrations.CreateModel(
            name='transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('numerodecomporbantes', models.CharField(blank=True, max_length=100)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=100)),
                ('bancoorige', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=30)),
                ('titularbanco', models.CharField(blank=True, max_length=100)),
                ('idcuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcuenta', to='cuenta.cuenta')),
                ('idnegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idnegocio', to='cuenta.negocio')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idproducto', to='cuenta.producto')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idusuario', to='cuenta.usuario')),
            ],
            options={
                'db_table': 'tb_transaccion',
            },
        ),
    ]
