# Generated by Django 4.1.4 on 2023-03-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_transaccion_descricion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='cod',
        ),
    ]
